# Generated by Django 4.1.3 on 2022-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empAttandance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('withdraw_amount', models.BigIntegerField()),
                ('attendance_date', models.DateField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('types', models.CharField(choices=[('Absent', 'Absent'), ('Half Present', 'Half Present'), ('Present', 'Present'), ('Tardy', 'Tardy')], max_length=100)),
            ],
        ),
    ]
