# Generated by Django 4.1.3 on 2022-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAttandance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empattandance',
            name='employee_name',
            field=models.CharField(choices=[('Mayur', 'Mayur'), ('Vivek', 'Vivek'), ('Bhupendra', 'Bhupendra')], max_length=100),
        ),
    ]
