# Generated by Django 4.1.3 on 2022-11-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=60)),
                ('employee_contact_number', models.BigIntegerField()),
                ('employee_address', models.TextField(max_length=150)),
                ('employee_salary', models.BigIntegerField()),
                ('employee_salary_type', models.CharField(choices=[('Per Day Basis', 'Per Day Basis')], max_length=50)),
                ('employee_attandance_type', models.CharField(choices=[('Per Day Basis', 'Per Day Basis')], max_length=50)),
                ('employee_attandance_count', models.BigIntegerField()),
                ('employee_total_amount', models.BigIntegerField()),
                ('employee_net_amount', models.BigIntegerField()),
            ],
        ),
    ]
