# Generated by Django 4.0.6 on 2022-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=60)),
                ('business_address', models.TextField(max_length=150)),
                ('business_mail', models.EmailField(max_length=40)),
                ('business_owner_name', models.CharField(max_length=30)),
                ('business_mobile_number', models.BigIntegerField()),
            ],
        ),
    ]
